package cn.study.entity;

import java.io.Serializable;

public class TtMail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail.mail
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail.titile
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail.content
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    private String content;

    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail.mail
     *
     * @return the value of tt_mail.mail
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    public String getMail() {
        return mail;
    }

    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail.mail
     *
     * @param mail the value for tt_mail.mail
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail.titile
     *
     * @return the value of tt_mail.titile
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail.titile
     *
     * @param titile the value for tt_mail.titile
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    public void setTitle(String titile) {
        this.title = titile == null ? null : titile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail.content
     *
     * @return the value of tt_mail.content
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail.content
     *
     * @param content the value for tt_mail.content
     *
     * @mbggenerated Mon Dec 06 22:18:03 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}