server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  mail:
    host: smtp.163.com
    username: job_zcc@163.com
    password: CCKTLRYWEUIINUVZ
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.study


